version: '3.9'

services:
  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    volumes:
      - ./docker/mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-secret}
      - MYSQL_DATABASE=${MYSQ_DATABASE:-playground}
